from pixel_art import *

compass = [
    NUL, NUL, NUL, BLU, BLU, NUL, NUL, NUL,
    NUL, NUL, BLU, LBU, LBU, BLU, NUL, NUL,
    NUL, BLU, LBU, LBU, RED, LBU, BLU, NUL,
    BLU, LBU, LBU, LBU, RED, LBU, LBU, BLU,
    BLU, LBU, LBU, BLK, LBU, LBU, LBU, BLU,
    NUL, BLU, LBU, BLK, LBU, LBU, BLU, NUL,
    NUL, NUL, BLU, LBU, LBU, BLU, NUL, NUL,
    NUL, NUL, NUL, BLU, BLU, NUL, NUL, NUL
]

dungeon_map = [
    BRN, BRN, BRN, BRN, BRN, BRN, BRN, BRN,
    PNK, PNK, BRN, BRN, BRN, BRN, PNK, BRN,
    BRN, PNK, PNK, PNK, BRN, BRN, PNK, BRN,
    PNK, BRN, PNK, PNK, PNK, PNK, PNK, BRN,
    PNK, PNK, PNK, PNK, PNK, PNK, PNK, BRN,
    PNK, BRN, PNK, PNK, PNK, BRN, BRN, BRN,
    BRN, PNK, PNK, PNK, BRN, PNK, PNK, BRN,
    BRN, BRN, BRN, BRN, BRN, BRN, BRN, BRN
]

small_key = [
    NUL, NUL, SLV, SLV, SLV, NUL, NUL, NUL,
    NUL, SLV, NUL, NUL, NUL, SLV, NUL, NUL,
    NUL, SLV, NUL, NUL, NUL, SLV, NUL, NUL,
    NUL, NUL, SLV, SLV, SLV, NUL, NUL, NUL,
    NUL, NUL, NUL, SLV, NUL, NUL, NUL, NUL,
    NUL, NUL, NUL, SLV, SLV, NUL, NUL, NUL,
    NUL, NUL, NUL, SLV, NUL, NUL, NUL, NUL,
    NUL, NUL, NUL, SLV, SLV, NUL, NUL, NUL
]
